"""
Builds a downloadable Markdown analysis report from session state:
deterministic profile + cleaning log + Q&A history (real computed results),
wrapped with an LLM-generated narrative summary.
"""
from __future__ import annotations

from datetime import datetime

from app.core import llm_engine, profiling


def build_report(
    dataset_name: str,
    df,
    cleaning_log: list[str],
    qa_history: list[dict],
) -> str:
    shape = profiling.basic_shape(df)
    cols = profiling.column_profile(df)

    structured_findings = {
        "dataset_name": dataset_name,
        "shape": shape,
        "columns": cols.to_dict(orient="records"),
        "cleaning_actions_applied": cleaning_log,
        "qa_history": qa_history,
    }

    try:
        narrative = llm_engine.generate_report_narrative(structured_findings)
    except llm_engine.LLMEngineError:
        narrative = "_(AI narrative unavailable — showing structured findings only.)_"

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    report = f"""# Data Analysis Report

**Dataset:** {dataset_name}
**Generated:** {generated_at}

---

## AI Summary

{narrative}

---

## Dataset Overview

- Rows: {shape['rows']}
- Columns: {shape['columns']}
- Duplicate rows found: {shape['duplicate_rows']}
- Memory footprint: {shape['memory_mb']} MB

## Column Profile

{cols.to_markdown(index=False)}

## Data Cleaning Actions Applied

{chr(10).join(f"- {item}" for item in cleaning_log) if cleaning_log else "- None"}

## Conversation Q&A Log

{chr(10).join(f"**Q:** {qa['question']}{chr(10)}**A:** {qa['answer']}{chr(10)}" for qa in qa_history) if qa_history else "_No questions asked this session._"}

---
_Report generated by AI-Powered Data Analyst Copilot. All numeric results were computed directly from the uploaded dataset via Pandas/SQL — not estimated by the AI._
"""
    return report
